language: php
dist: trusty

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer tests
